# Generated by Django 3.0.5 on 2020-08-17 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 17, 13, 20, 58, 455324), null=True),
        ),
    ]
