# Generated by Django 3.0.5 on 2020-08-19 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_auto_20200817_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 12, 26, 7, 94849), null=True),
        ),
    ]
