# Generated by Django 3.0.5 on 2020-08-19 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_auto_20200819_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 13, 5, 34, 615372), null=True),
        ),
    ]
